// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUpOGEcTbI4F2JFpLBw6Ka7vpgeh9RNH4',
    appId: '1:973827174115:web:f7af0013dc068450de1fd6',
    messagingSenderId: '973827174115',
    projectId: 'better-life-ae7f1',
    authDomain: 'better-life-ae7f1.firebaseapp.com',
    storageBucket: 'better-life-ae7f1.firebasestorage.app',
    measurementId: 'G-YPY8412VZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHqIWcwSQ7hWgpFeP5VdJolyzkLZNpmNc',
    appId: '1:973827174115:android:0cffc2720307d8c0de1fd6',
    messagingSenderId: '973827174115',
    projectId: 'better-life-ae7f1',
    storageBucket: 'better-life-ae7f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHnUz-9VWWzzNKGUg5_CnEDaiHPT3hWoA',
    appId: '1:973827174115:ios:47c7a19db421c2b1de1fd6',
    messagingSenderId: '973827174115',
    projectId: 'better-life-ae7f1',
    storageBucket: 'better-life-ae7f1.firebasestorage.app',
    iosBundleId: 'com.example.betterLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHnUz-9VWWzzNKGUg5_CnEDaiHPT3hWoA',
    appId: '1:973827174115:ios:47c7a19db421c2b1de1fd6',
    messagingSenderId: '973827174115',
    projectId: 'better-life-ae7f1',
    storageBucket: 'better-life-ae7f1.firebasestorage.app',
    iosBundleId: 'com.example.betterLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUpOGEcTbI4F2JFpLBw6Ka7vpgeh9RNH4',
    appId: '1:973827174115:web:ae5bd0180b13c045de1fd6',
    messagingSenderId: '973827174115',
    projectId: 'better-life-ae7f1',
    authDomain: 'better-life-ae7f1.firebaseapp.com',
    storageBucket: 'better-life-ae7f1.firebasestorage.app',
    measurementId: 'G-8QGJDE40CS',
  );

}